

function block_more_link_form_block_admin_configure_alter(&$form,&$form_state){
    $default_more_link_url = '';
    $default_more_link_title = '';
    $form['settings']['more_link_url'] = array(
        '#type' => 'textfield',
        '#title' => t('More Link Url'),
        '#maxlength' => 255,
        '#description' => t('The More Lunk Url of the block as shown to all user.'),
        '#default_value' => $default_more_link_url,
        '#weight' => -17, 
    );
    
    $form['settings']['more_link_title'] = array(
        '#type' => 'textfield',
        '#title' => t('More Link Title'),
        '#maxlength' => 255,
        '#description' => t('The More Lunk Url of the block as shown to all user.'),
        '#default_value' => $default_more_link_title,
        '#weight' => -17,
   
    );
    $form['#validate'][] = 'block_more_link_block_admin_configure_validate';
    $form['#submit'][] = 'block_more_link_block_admin_configure_submit';

}
